### ISSUE TITLE
NavBar 기능 작업

### ISSUE THREAD

**Issue by BearHumanS** [AIGOO-Epson/backend#7]
NavBar 페이지 라우팅 기능 작업 (스타일 X)

**Comment by antegral** [comment]
본 레포지토리는 Backend고, 해당 이슈는 Frontend 작업이므로 close 하겠습니다.

**Comment by antegral** [comment]
본 레포지토리는 Backend고, 해당 이슈는 Frontend 작업으로 추정되므로 이슈 닫겠습니다.
